### ISSUE TITLE
Recipes missing after update to 0.0.61

### ISSUE THREAD

**Issue by Gen732741** [railcraft-reborn/railcraft#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

After updating game to 0.0.61, many Create recipes are missing.  If recipe component is selected and uses for that item shown, item shows as craftable.  Unable to search individual items to find them or recipe.  Examples are hose pulley, fluid pipe, and mechanical pump (all from create).  Have attempted restart multiple times and recipes do not show up.

### Configuration

```Markdown
- Mod version:0.0.61
- NeoForge/Forge version:
- Minecraft version:
- Are you playing on a server?:n
```

### To Reproduce

Open JEI.
Search for mechanical pump or fluid pipe or hose pulley.
No recipes from create for those items shown.

Select copper plate and show uses for it.
Fluid pipe and hose pulley show as available crafts.

Select fluid pipe from list of craftable items from copper plate craftables and show uses.
Mechanical pump shows as available craft.

### Expected behavior

When searching items, should show as available in JEI.

**Comment by Edivad99** [comment]
It's a create issue, not a railcraft issue
