### ISSUE TITLE
Switch tracks don't change rotation of tracks around them correctly

### ISSUE THREAD

**Issue by CyanideCarrot** [railcraft-reborn/railcraft#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When I place a switch track, the tracks around them don't rotate and don't line up

### Configuration

```Markdown
- Mod version: 1.0.3
- NeoForge/Forge version: 47.1.44
- Minecraft version: 1.20.2
- Are you playing on a server?: No
```

### To Reproduce

See video below

### Expected behavior

Switch tracks should adjust the orientation of tracks next to them to connect properly

### Screenshots & Video

https://youtu.be/1Yr_Npksreg

**Comment by Edivad99** [comment]
I should have fixed the problem. I ask you to try using this jar and to reopen the issue if there are still problems.
https://github.com/railcraft-reborn/railcraft/suites/15647368332/artifacts/893090808

**Comment by CyanideCarrot** [comment]
Better, but still having some problems
https://youtu.be/GGF1-EnmmHw

**Comment by Edivad99** [comment]
https://github.com/railcraft-reborn/railcraft/suites/15770672470/artifacts/900172231
