### ISSUE TITLE
Switch motors don't respond to redstone

### ISSUE THREAD

**Issue by CyanideCarrot** [railcraft-reborn/railcraft#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Switch motors (including routing variant) don't activate when powered with redstone

### Configuration

```Markdown
- Mod version: 1.0.3
- NeoForge/Forge version: 47.1.44
- Minecraft version: 1.20.2
- Are you playing on a server?: No
```

### To Reproduce

Place switch motor next to switch track
Place redstone torch next to motor

### Expected behavior

Motor should change the direction of the switch track

**Comment by Edivad99** [comment]
Did you hit the "Redstone Triggered" button?
<img width="369" alt="Screenshot 2023-08-30 alle 11 13 49" src="https://github.com/railcraft-reborn/railcraft/assets/25778604/872c67a0-82bd-4473-9ce8-4908f7038899">
