### ISSUE TITLE
Rock Crusher should crush metal ores

### ISSUE THREAD

**Issue by gardenappl** [railcraft-reborn/railcraft#108]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

[1.12 RailCraft had the ability to process metal ores into IC2 dusts using the Rock Crusher.](https://github.com/Railcraft/Railcraft/blob/34416755a312fd0ba6813d9a80169fe56dab369f/src/main/java/mods/railcraft/common/modules/ModuleFactory.java#L409) The current version processes dust and gem ores but not metals.
Maybe RailCraft should add its own metal dusts? Or perhaps allow an item tag to be used as recipe output and then check for first (if any) item in that tag. Personally I'd prefer the first option, since the second option could cause issues with unification scripts in big modpacks.

**Comment by gardenappl** [comment]
At the very least, ore blocks -> raw materials should be possible with little extra work.

**Comment by Edivad99** [comment]
I would like to understand better, do you mean processing the iron ore to make it raw iron?

**Comment by gardenappl** [comment]
I'd prefer processing _raw material -> dust_, like other tech mods. I'm just saying that processing _ore block -> raw material_ might be easier to implement because then RailCraft won't have to add metal dusts.

**Comment by Edivad99** [comment]
I think this is quite unfeasible, as for every mod that adds a new type of ingot we would have to add a new variant of dust. I'm keeping this issue open as a reminder

**Comment by gardenappl** [comment]
I agree that adding processing for *all metals* is out of scope for RailCraft, but you really don't need to do that. I'm only asking for vanilla ores and RailCraft ores. I mean, you already have recipes for redstone, coal and diamonds, but nobody's asking to implement every gem or every dust, etc.

**Comment by tomodachi94** [comment]
Food for thought:

Add dusts for vanilla ores, but only enable them if there's no other mod that adds them (tags could be useful here). Most tech mods that add ores also add dusts, so there should be no need for adding dusts for modded items.

**Comment by gardenappl** [comment]
Mod compatibility and item redundancy shouldn't be a concern for RailCraft. There are other mods that can handle this (AlmostUnified, JAOPCA, or KubeJS scripting). JAOPCA can automatically add recipes and dusts for crushing modded metals, the dev is only waiting for RailCraft to implement vanilla metal crushing. See https://github.com/TheLMiffy1111/JAOPCA/issues/288

**Comment by Edivad99** [comment]
@gardenappl I'm back, in the 1.20.4 branch I managed to implement the recipes that are enabled only when the items that match the required tags are present.
So you should be able to use the crusher even with items that are not part of the railcraft, such as in this case the lead dust

![Screenshot 2024-02-09 alle 13 31 38](https://github.com/railcraft-reborn/railcraft/assets/25778604/691ba097-515f-4acd-987d-9ed1bf6a1d39)

**Comment by Edivad99** [comment]
UPDATE: Also in the next version for 1.20.1

**Comment by gardenappl** [comment]
Cool, thank you!
