### ISSUE TITLE
Guided visualization of multiblock structures

### ISSUE THREAD

**Issue by The7Alchemist** [railcraft-reborn/railcraft#113]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

So i can find any way to see the railcraft reborn multiblock structures so i was wondering if there could be like a book with the multiblock structure quides and other railcraft information.

**Comment by Edivad99** [comment]
I like the idea, we could implement it with Patchouli
https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/multiblocks
