### ISSUE TITLE
AEInfinityBooster Bug

### ISSUE THREAD

**Issue by DOsorio04** [railcraft-reborn/railcraft#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When you use a card from AEInfinityBooster you can't send or retrive more that a 32 ou 16 item (32 for the dimensional card and 16 for the infinity range booster) from your network using wireless terminals, but when you use the Wireless Booster from AE2 it works perfectly

### Configuration

```Markdown
- Mod version:
- NeoForge/Forge version:
- Minecraft version:
- Are you playing on a server?:
```

### To Reproduce

Make a Simple AE2 Network
Make the ME Wireless Access Point and upgrade it with a AEInfinityBooster card
Try to use a wireless terminal to put ou take items from your network

### Expected behavior

You will not be able to imput ou output 64 items per operation on wireless terminals

**Comment by Edivad99** [comment]
This bug has nothing to do with Railcraft Reborn. Be more careful next time!
