### ISSUE TITLE
Items are misplaced in the REI recipe preview for the Rolling Machine

### ISSUE THREAD

**Issue by Rundas01** [railcraft-reborn/railcraft#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Input and Output items are not in their correct space (see screenshot).

### Railcraft Reborn version

1.0.2

### NeoForge/Forge version

47.1.44

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1) Open REI
2) Press the assigned hotkey for "uses" on the Rolling Machine or the one for "recipe" on any item that is crafted in the Rolling Machine
3) Experience the Bruh Moment xD

### Expected behavior

The items should be shown in their correct position.

### Screenshots & Video

![Screenshot (472)](https://github.com/railcraft-reborn/railcraft/assets/38040866/f345edc5-5319-4b0f-8e23-f4b742d8c92f)

**Comment by Edivad99** [comment]
We have added support only for JEI. If REI doesn't work it's their problem.
https://github.com/railcraft-reborn/railcraft/blob/1.20.x/src/main/java/mods/railcraft/integrations/jei/category/RollingRecipeCategory.java

**Comment by Edivad99** [comment]
What I mean is that if REI is able to recognize the rolling machine recipes it is because in some way it is able to interpret the JEI recipes. So it's their problem to line up the items correctly.
At least that's what I think...

**Comment by josephtarbit** [comment]
Yeah seems to be a rendering bug in REI.

**Comment by Edivad99** [comment]
@Rundas01 open an issue at [REI](https://github.com/shedaniel/RoughlyEnoughItems)
