### ISSUE TITLE
Crash when placing rail at both sides of turnout track

### ISSUE THREAD

**Issue by Neuron67** [railcraft-reborn/railcraft#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

placed a rail next to turnout track that was already connected by another rail on the opposite side and crashed.
I was working on changing models to 3D at the time so that may have contributed to the crash. I'm not sure.

### Railcraft Reborn version

1.0.7

### NeoForge/Forge version

47.1,47

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

place rail, use maul to change to turnout track, connect rail, place rail opposite side of turnout track

### Expected behavior

thought I would break first connected rail and turnout would flip to other side.

### Logs & Environment

```Shell
no crash log created
```

**Comment by Edivad99** [comment]
Can you take a video or photo, I can't reproduce the bug

**Comment by Neuron67** [comment]
I was able to reproduce and got crash log
[Reproduced crash.txt](https://github.com/railcraft-reborn/railcraft/files/12671523/Reproduced.crash.txt)

**Comment by Edivad99** [comment]
Give me a photo of how you placed the rails

**Comment by Neuron67** [comment]
well I tried a few times to recreate the crash  so not certain of the placement

**Comment by Neuron67** [comment]
![2023-09-20_03 46 58](https://github.com/railcraft-reborn/railcraft/assets/24964976/87e73fa9-ae9f-4e1b-9e29-fcdb0771fc6e)

**Comment by Neuron67** [comment]
oh, it just occurred to me that it might have to do with my 3d models

**Comment by Neuron67** [comment]
try this
![rail placement](https://github.com/railcraft-reborn/railcraft/assets/24964976/2dfecbf4-cdd0-4746-9ca5-c19f1a4c9cbb)

**Comment by Edivad99** [comment]
Ok, fixed

**Comment by Neuron67** [comment]
oh cool, so not my models then, phew

**Comment by Neuron67** [comment]
thanks
