### ISSUE TITLE
Client log being spammed with [13:31:44] [Worker-Main-228/WARN] [mo.ra.wo.le.bl.en.mu.MultiblockBlockEntity/]: getMembership is server-side only.

### ISSUE THREAD

**Issue by ProsperCraft** [railcraft-reborn/railcraft#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

![image](https://github.com/railcraft-reborn/railcraft/assets/4427684/a77e0d34-efea-4577-bf48-9991f9f16137)

### Railcraft Reborn version

railcraft-reborn-1.20.1-1.0.7

### NeoForge/Forge version

forge-1.20.1-47.1.3

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Connect to a server with multiblocks built in it.

### Expected behavior

It not call serversided code on client.

**Comment by Edivad99** [comment]
The problem is the cable you are using which is using client side cabapilities. I remove the warning, but YOU have to open the issue in the cable mod!

**Comment by McJty** [comment]
There is NOTHING wrong with using capabilities client-side. This is not a bug in XNet. You should handle this gracefully at client side too
