### ISSUE TITLE
Can't make standard rail

### ISSUE THREAD

**Issue by stolenvw** [railcraft-reborn/railcraft#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

To make standard rail you need rail, to make rail you need standard rail.  How do you make rail or standard rail when to make one you need the other.

### Railcraft Reborn version

1.0.8

### NeoForge/Forge version

47.2.1

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

click recipe to make rail, needs standard rail
click recipe to make standard rail, needs rail

### Expected behavior

be able to make rail, or standard rail

**Comment by Edivad99** [comment]
You can use the rolling machine
<img width="457" alt="Screenshot 2023-10-01 alle 20 55 06" src="https://github.com/railcraft-reborn/railcraft/assets/25778604/b5188f29-5880-49f3-bd46-5f698e9d5885">
