### ISSUE TITLE
Iron trapdoors are blasted into 6 steel ingots

### ISSUE THREAD

**Issue by medsal15** [railcraft-reborn/railcraft#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Iron trapdoors are crafted with 4 iron ingots but are blasted into 6 steel ingots.

### Railcraft Reborn version

1.0.8

### NeoForge/Forge version

47.1.47

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

- Craft an iron trapdoor with 4 iron ingots.
- Put it in a blast furnace multiblock.
- Get 6 steel ingots and 6 granulated slag.

### Expected behavior

Iron trapdoors should be blasted into 4 steel ingots.

### Screenshots & Video

![screenshot from jei showing an iron trapdoor being blasted into 6 steel ingots](https://github.com/railcraft-reborn/railcraft/assets/8267354/95f6d30d-55fc-4c63-aba2-35162bff1c34)

**Comment by Edivad99** [comment]
If you look at 1.12 the recipe is the same. But I also think it would be better to put 4 pieces instead of 6. I'll change it!
