### ISSUE TITLE
Signals Not Behaving As Intended

### ISSUE THREAD

**Issue by Multi-Coder-24** [railcraft-reborn/railcraft#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

I have tried to create a loop with block signals however once I link 2 signals together if I attempt to link a 3rd onto the chain it resets the link. And because of that behaviour it cannot be used as intended
Example I have signal A,B,C and they run in that order
I link A-B, all works well.
I link B-C, and it drops the link for A-B

### Railcraft Reborn version

1.0.8

### NeoForge/Forge version

47.2.1

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Create a stretch of track
2. Add 3 signals one at each end and one in the middle
3. Link one end to the middle
4. link the middle to the other end
5. the first link gets dropped.

### Expected behavior

The signals should connect and form a chain of blocks

**Comment by Edivad99** [comment]
You can't link more than two block signals together, the exception is the Signal Block Relay Box

**Comment by Multi-Coder-24** [comment]
Oh goodness, I was completely mis-remembering how the signals work
