### ISSUE TITLE
Iron doors are blasted into 6 steel ingots

### ISSUE THREAD

**Issue by medsal15** [railcraft-reborn/railcraft#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

3 iron doors are crafted with 6 iron ingots, but are blasted into 6 steel ingots each.

Yes, the issue is similar to #131.

### Railcraft Reborn version

1.0.8

### NeoForge/Forge version

47.2.3

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

- Craft 3 iron doors with 6 iron ingots.
- Put them in a blast furnace multiblock.
- Get a total of 18 steel ingots and 18 granulated slag.

### Expected behavior

Iron doors should be blasted into 2 steel ingots each

### Screenshots & Video

![image](https://github.com/railcraft-reborn/railcraft/assets/8267354/dcd41f4a-5b9f-46b7-bb0b-674ea3ca0431)

**Comment by Edivad99** [comment]
Already fixed in https://github.com/railcraft-reborn/railcraft/commit/37468bd7d62dd7c9b621f5b89dc7aca44c4377c2

**Comment by medsal15** [comment]
It doesn't seem to, according to [the recipe generator](https://github.com/railcraft-reborn/railcraft/blob/1.20.x/src/main/java/mods/railcraft/data/recipes/providers/BlastFurnaceRecipeProvider.java#L56)

**Comment by Edivad99** [comment]
Oops, I got confused with another recipe I had fixed
