### ISSUE TITLE
Game crashes on startup with minecart ticking issues

### ISSUE THREAD

**Issue by YukiRainee** [railcraft-reborn/railcraft#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

java.lang.IllegalStateException: RollingStock missing on MinecartChest['Minecart with Chest'/20, l='ServerLevel[New World]', x=-28.50, y=0.50, z=174.50]
--
8 | at mods.railcraft.api.carts.RollingStock.lambda$getOrThrow$0(RollingStock.java:65) ~[railcraft-reborn-1.20.1-1.0.9.jar%231059!/:1.20.1-1.0.9] {re:mixin,re:classloading}

java.lang.IllegalStateException: RollingStock missing on MinecartChest['Minecart with Chest'/20, l='ServerLevel[New World]', x=-2[8](https://mclo.gs/2eH7s66#L8).50, y=0.50, z=174.50]
	at mods.railcraft.api.carts.RollingStock.lambda$getOrThrow$0(RollingStock.java:65) ~[railcraft-reborn-1.20.1-1.0.9.jar%231059!/:1.20.1-1.0.9] {re:mixin,re:classloading}

### Railcraft Reborn version

1.0.9

### NeoForge/Forge version

47.1.79

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

Attempt to generate world after starting minecraft 
wait and then check crash logs

### Expected behavior

To be able to load into a world with minimal issues

### Logs & Environment

```Shell
https://mclo.gs/2eH7s66
```

**Comment by josephtarbit** [comment]
@Rainee4563 Could you let me know what world seed you used to obtain this crash?

**Comment by josephtarbit** [comment]
Or does this occur with every world you generate?
