### ISSUE TITLE
firestone fire visually stuck

### ISSUE THREAD

**Issue by jlp1528** [railcraft-reborn/railcraft#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Fires spawned from firestone ore and raw firestone are mostly only visual. I have tested this by tossing in cobblestone and it doesn't burn most of the time. Furthermore, while the few real fires seem to go away, all the fake ones get visually and audibly stuck until a block is placed in their position.

### Railcraft Reborn version

1.0.9

### NeoForge/Forge version

NeoForge 47.1.76

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Pick up firestone ore or raw firestone.
2. Fire everywhere.
3. Put away the item that sets fire to your surroundings.
4. Most of the fire does not go away even when left clicking on it.

### Expected behavior

Fire should not get stuck like this.

**Comment by josephtarbit** [comment]
Fixed by 9b67728abae6312553b290ecd5e8ad361e97cd9c
