### ISSUE TITLE
Dual-Head Distant Signal not function properly

### ISSUE THREAD

**Issue by Tavren** [railcraft-reborn/railcraft#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Dual-Head Distant Signal bottom lamp blinks yellow after getting bound to second Signal Controller Box instead of show signal aspect from that controller, both controllers controls only top lamp.

After restarting the world bottom lamp just show solid green but yet not controlled by the controller, both of them still weirdly controls the top lamp only

### Railcraft Reborn version

1.0.9

### NeoForge/Forge version

47.1.76

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place Dual-Head Distant Signal
2. Place two Signal Controller Box (or Analog Signal Controller Box)
3. Place a lever or button for each Controller Box for change the signal aspect they provide with redstone
4. Using Signal Tuner right click on one Controller Box, then on Dual-Head Distant Signal to link them
5. Using Signal Tuner right click on second Controller Box, then on Dual-Head Distant Signal to link them
6. (If using Analog Controller then right click on it and set for example green aspect to be send when redstone level is 15)
7. Using Levers or Buttons byt the controllers we can control the lamp that will show that signal aspect from controllers, but only top lamp is working and from the both, lower one just blink yellow

### Expected behavior

Dual-Head Distant Signal should bound to two Signal Controllers and show the signal aspect they provide on separate lamps

### Screenshots & Video

![284812902-b3fd0cbd-dc8d-4205-981f-0234cdaef8a5](https://github.com/railcraft-reborn/railcraft/assets/6377052/bc884d70-949d-4534-88e5-6f841528e8a6)

**Comment by josephtarbit** [comment]
The dual head signal is comprised of a distant signal and a block signal so it can only be connected to one controller. The secondary signal needs to be connected to another block signal.

**Comment by josephtarbit** [comment]
> The dual head signal is comprised of a distant signal and a block signal so it can only be connected to one controller. The secondary signal needs to be connected to another block signal.

Never mind me, I'm forgetting the mod now has multiple types of dual head signal...

**Comment by josephtarbit** [comment]
Fixed by [c406cf3](https://github.com/railcraft-reborn/railcraft/commit/c406cf377e814ef6fdaa5f5e7771d0c7de9a7378)
