### ISSUE TITLE
cant use rolling block and cant extract croeasote oil 

### ISSUE THREAD

**Issue by AsheX1** [railcraft-reborn/railcraft#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

this is on neoforge 1.20.1
menual rolling machine cant put in any items or maybe 1 some times but never all the ones needs to roll some rails
coke oven hard time getting coal to go in and cant put buckets or even bottles to get  croeasote oil  out of it 

the log is not showing anything

trying shift clicking does not seems to do anything also

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

neoforge 47.1.88

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

/

### Expected behavior

get the oil and rails

### Logs & Environment

```Shell
nothing
```

**Comment by AsheX1** [comment]
i can make iron rails it seems but its a rail pain but out out sorting or something

**Comment by Edivad99** [comment]
Can you be more specific?
I can extract the creosote both in a bucket and in a bottle.
The manual rolling machine works in the tests I've done, can you tell me what's wrong?

**Comment by AsheX1** [comment]
let me get a quick recording

**Comment by AsheX1** [comment]
here is short video for the manual rolling machine
https://youtu.be/cpk-IAq5AUA
as you can see i right click drag or even left click just do not nothing then im trying left and right click and some times it wil put 1 item in or the full stack

**Comment by AsheX1** [comment]
and here is a link for the croeasote oil
https://youtu.be/2cNZT_qjJdc
also as you can see there is idk what it is lag or something its does not seems or feel like lag wen i take out the block of coal coke i can not put the buckets back in my bag i try to click to put them in a spot but nothing is happing have to press esc to close  the gui and then is back to normal

i have no idea whats going but for now im gone make a crafttweaker script to get around the problem (use something els to make the oil and rails)

**Comment by AsheX1** [comment]
oke it is working now u update embeddium from 0.2.16 to 0.2.18
it is now working in single player and multi players
but there is still the weird lag problem in inventory and the dum ass auto balancing on the rolling rolling machine 

i dont know why this is even in the mod auto balancing items for the rolling machine just let it act like an crafting tablet think this is the problem why dragging items does not work and placing item in it also i think that is the reason why its so buggy

and then there is still the strange delay/lag wen putting an item in bag or moving it in the bag

**Comment by AsheX1** [comment]
the main problem right now that i see is the rolling machine it needs to act as a crafting table and not do auto balancing crap

**Comment by AsheX1** [comment]
and cant pull out croeasote oil again why log is not showing anything from server or client

**Comment by Edivad99** [comment]
For the creosote thing, it only works if you put one bucket at a time. I'm doing some testing to see if it makes sense to remove this limit.
https://github.com/railcraft-reborn/railcraft/blob/5dcf7c3618c262cd1fe01fc5448ae458bfaf904b/src/main/java/mods/railcraft/world/inventory/slot/EmptyFluidContainerSlot.java#L17

As for the question of item drag, it is not just a problem of the rolling machine, but of all the GUI that railcraft adds, it must be investigated.

**Comment by halvors** [comment]
I can confirm the laggy UI's, mostly works in the end, but it is a pain

**Comment by Edivad99** [comment]
@halvors Try using this JAR and tell me if I managed to solve the problem

**Comment by Edivad99** [comment]
UPDATE: Use this https://github.com/railcraft-reborn/railcraft/actions/runs/7826844969/artifacts/1229495264

**Comment by Edivad99** [comment]
@AsheX1

**Comment by AsheX1** [comment]
oke gone look at it tomorrow

**Comment by AsheX1** [comment]
oke test 1 manual rolling machine works now no strange weirdness it just works dragging items testing coke oven now gone need a a few min

**Comment by AsheX1** [comment]
coke oven also works now can shift click buckets in single or a stack of buckets or just put it them by clicking 

AND the UI lag is also gone

@Edivad99 not gone close the issue until you see it or you close it

also neoforge 47.1.97 there is an update for neoforge to 47.1.99 but i dont think that is gone matter

**Comment by AsheX1** [comment]
oke i dont know if this is on railcraft or an other mod but dont use neoforge 47.1.98 or 47.1.99

` - `47.1.99` Fallback to magic damage on clientside when connecting to vanilla (#617)
 - `47.1.98` Bump FML (#612)`

what ever they changed now makes the game crash's staying on 47.1.97

the crashlog is not very usefull so gone test some more but i doubt this is a railcraft problem

**Comment by Edivad99** [comment]
Great, now I'm merging.
From what I know it is better to use forge/neoforge 47.1.3 because it was the last version before the fork. And since we need to ensure compatibility between NeoForge and Forge that's the version we use
