### ISSUE TITLE
Is it possible to automate the rolling machine?

### ISSUE THREAD

**Issue by halvors** [railcraft-reborn/railcraft#163]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

Is it possible to automate the rolling machine? Can i interface with it from each side etc? Seems to be not possible?

**Comment by Edivad99** [comment]
Only the powered rolling machine can be automatize

**Comment by halvors** [comment]
Thx, managed to automate it now, that being said recipe needs to be static per rolling machine, so 1 machine per recipe in case of Refined Storage or AE2

**Comment by drivetheory** [comment]
the only UGLY way i got this to work was setting the pattern in the machine and then using an ME Export Bus, a AE2 Redstone Card, an AE2 Crafting Card, an ME Level Emitter, and an ME Import Bus...

this machine REALLY needs to be made more compatible with the AE2 Pattern Provider block
https://guide.appliedenergistics.org/1.20.1/items-blocks-machines/pattern_provider

3 blocks vs 1 block
