### ISSUE TITLE
The high speed electric track and high speed electric junction track have identical recipes

### ISSUE THREAD

**Issue by halvors** [railcraft-reborn/railcraft#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The high speed electric track and high speed electric junction track have identical recipes.

https://github.com/railcraft-reborn/railcraft/blob/5dcf7c3618c262cd1fe01fc5448ae458bfaf904b/src/generated/resources/data/railcraft/recipes/high_speed_electric_track.json

https://github.com/railcraft-reborn/railcraft/blob/5dcf7c3618c262cd1fe01fc5448ae458bfaf904b/src/generated/resources/data/railcraft/recipes/high_speed_electric_junction_track.json

I propose changing high speed electric junction track to have a "cross" of electric rail.

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.1.96

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Try to craft high speed electric track, it results in high speed electric junction track, since out of the two identical recipes this seems to "win"

### Expected behavior

Only one output for a given recipe

**Comment by Edivad99** [comment]
Nice catch!
