### ISSUE TITLE
Locomotives deals damage to players with armor, protecting from any damage source like MekSuit from Mekanism

### ISSUE THREAD

**Issue by halvors** [railcraft-reborn/railcraft#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Locomotives deals damage to players with armor, protecting from any damage source like MekSuit from Mekanism.

Railcraft should deal damage using a damagesource that can be prevented by other mods.

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.1.96

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Setup and start a Locomotive with a MekSuit equipped (from Mekanism)
When hit by the train you die, even though the suit prevents damage from any damage source

### Expected behavior

Not dealing damage when damagesource is preveneted by armor.

**Comment by Edivad99** [comment]
It's a design choice to kill the player.
