### ISSUE TITLE
Impossible to change rotation of a throttle track, all variants

### ISSUE THREAD

**Issue by halvors** [railcraft-reborn/railcraft#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

It is impossible to change rotation of a throttle track, all variants. Using a wrench on it rotates it but only between North and East. Impossible to rotate it to go NORTH or WEST.

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.1.96

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Place a throttle track, try rotate it with a wrench, it will only rotate between NORTH and EAST direction.

### Expected behavior

Throttle track rotating between all 4 directions, NORTH, SOUTH, EAST and WEST.

**Comment by Edivad99** [comment]
Yeah, it is a bug also in 1.12.2

**Comment by halvors** [comment]
Is there a workaround for this? Or is it just impossible to slow down returning trains from high speed tracks?

**Comment by halvors** [comment]
This also affects many other tracks, they can only be rotated NORTH/EAST

**Comment by Edivad99** [comment]
The rails themselves only point NORTH or EAST.
To see if it's a bug you have to see if you can change the arrows with the crowbar

**Comment by halvors** [comment]
I can change the arrows, but still it does not seem to take arrow's direction into account when a train hits it

**Comment by halvors** [comment]
@Edivad99 After some more testing it turns out it kindof works if orienting the arrows and the track itself EAST, it will change throttle of trains going EAST to WEST, even though arrows point EASTWARDS. Changing arrows to point WESTWARD will redirect trains driving WEST back EAST.

**Comment by Edivad99** [comment]
So can we close this issue?
