### ISSUE TITLE
Add a config to disable some ore generation

### ISSUE THREAD

**Issue by MOLJOLL** [railcraft-reborn/railcraft#172]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

Please add a config to control ore generation, at least allow the player to completely disable the generation of a type of the railcraft ores.
When I was trying to make a modpack with Railcraft and Thermal Series (and Create), it was a mess that these three mods were trying to generate the same ores. Although they are sharing the same tags (or ore dictionary for old versions), but it isn't that balanced, the density of the ores is not that reasonable.
By the way, I'm just wondering that do you have the plan of updating the ores' texture for "1.17+ style".
English is not my mother tongue, so please ignore my mistakes.

**Comment by Edivad99** [comment]
The concept of config that disables ore generation no longer exists, everything is done from json files.
You have two options:
- you modify the files inside the jar file
- or you create a datapack that overwrites the contents of the files.

As for textures, we are open to collaborating with someone who knows about graphics to modernize the mod.

**Comment by Edivad99** [comment]
I'll leave this comment pinned in case anyone has the same question and anyone who wants to contribute with graphics can leave a comment below.

**Comment by MOLJOLL** [comment]
Oh, I didn't notice that. Anyway, thank you!

**Comment by TheEndermage220** [comment]
Deleting the related json files for ore gen from the jar causes the game to crash upon the mouseclick for create new world. I tried a few angles, including attempting to make a datapack, but I cannot get it to cooperate. Having some feature that makes it easy to disable ore gen for those of us who are not adept coders would be an excellent feature. I can attach the most recent cresh log if you believe that would be helpful.

**Comment by MOLJOLL** [comment]
You could simply edit the file with notepad, set the value of “size” into 0.
The crash also happened when I tried to delete the file, so deleting the file is not effective.

**Comment by Shockflare** [comment]
Have anyone figured out how to disable the ores? I don't have time to learn about or make datapacks or mess with the code. If anyone has any information on how to work around this without code it would be much appreciated.

**Comment by jdinkel** [comment]
Could someone give an example of how to do this with a datapack?  I would rather add a datapack than mess with the jar.

Update:

So far, if I have it right.  I need to create a zip file that contains a pack.MCMETA file (I just copied from the Railcraft Reborn jar and changed the description value) and the data/railcraft/worldgen/ configured_feature and placed_feature folders copied out of the jar.  I then changed every instance of "size" in every file in the configured_feature folder to 0 and every instance of "count" in every  file in the placed_feature folder to 0.

I then zipped it up and added it as a datapack when creating a world.  The world hasn't crashed anyway.  Testing out with a quarry now.

Update 2:

it works

**Comment by RConTRS** [comment]
could you guys please do us a favor and just reintroduce those settings? i wasted long hours trying to make kubejs/datapacks work but to no avail, just let us simply change settings like normal mods do.

**Comment by sofka1337** [comment]
> could you guys please do us a favor and just reintroduce those settings? i wasted long hours trying to make kubejs/datapacks work but to no avail, just let us simply change settings like normal mods do.

unpack .jar of RC, in data\railcraft\forge\biome_modifier find .json files named for like "add_lead_ore", copy all these files to .minecraft\kubejs\data\railcraft\forge\biome_modifier path (or create it) and replace "type": "forge:add_features" to "type": "forge:none", that's it.
you can control which ores will be generate (for example i left firestone ores)

**Comment by RConTRS** [comment]
i found out about this myself ty, i was trying to do for chest loot but i have enough basic knowledge to do similar thing for anything else like that.

**Comment by Paprika7x** [comment]
I want to draw textures for ore, but I do not know how to get textures from a file (I used to draw only skins). I'd appreciate some help.

**Comment by RConTRS** [comment]
this is not the place to ask any questions at all, you better google that or ask in some minecraft discord server.
