### ISSUE TITLE
Tunnel Borer is not filling more than one linked chest, or taking rails or gravel from linked chests.

### ISSUE THREAD

**Issue by Gfy31** [railcraft-reborn/railcraft#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Tunnel Borer is not filling more than one linked chest, or taking rails or gravel from linked chests.  When the first chest is full the borer starts throwing the items it bores away.  

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.2.0

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place Tunnel Borer on rail 2. link chest carts 3.give firestone, gravel, rails and diamond head to borer in interface. 

### Expected behavior

the linked carts to be filled after the previous one is full and the borer takes rails and firestones and gravel and perhaps even diamond tunnel bore head, basically anything it requires to work.  In 1.12 I was putting extra supplies in the back chest carts, so the borer could take them when it ran out

### Screenshots & Video

![Borer throwing away cobblestone](https://github.com/railcraft-reborn/railcraft/assets/38654660/bf95943a-cea2-4354-aa2d-d4dfb171c2e3)

**Comment by Edivad99** [comment]
This is a consequence of this bug #145
My suggestion is to put glasses on and set them to "Shunting".
Then you have to make sure that the lines are similar to those in the photo.
![2024-02-23_11 41 40](https://github.com/railcraft-reborn/railcraft/assets/25778604/2d5455a6-bab8-4ac7-a48e-7aa0fefd30a8)
We are working on a fix, but it takes time
