### ISSUE TITLE
Detectors outputting redstone singal on all sides.

### ISSUE THREAD

**Issue by vexxmage** [railcraft-reborn/railcraft#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Detectors ouput redstone signal on all side when it should only output on the side with the dot.

### Railcraft Reborn version

1.20.x

### NeoForge/Forge version

47.1.63

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

rail with loco on it.
loco detector next to it.
Redstone on each side of the detector. (The redstone is not connect together)

### Expected behavior

Only the side with the dot on the detector should get a signal.

**Comment by Edivad99** [comment]
Already fixed https://github.com/railcraft-reborn/railcraft/commit/8db6a528a5709ec65a7c4f7a66cebb165ceb7289
