### ISSUE TITLE
Switch track bug on diagonal tracks

### ISSUE THREAD

**Issue by greeeen-dev** [railcraft-reborn/railcraft#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When attempting to create a switch track with a spike maul, the curved track next to the switch track becomes a straight track, disconnecting it from the diverging line.

Track layout before switch track:
![2024-02-24_22 44 26](https://github.com/railcraft-reborn/railcraft/assets/41323182/8fa83789-c607-45b9-803a-1423110ca977)

Track layout after, version 1.0.2:
![2024-02-24_22 44 38](https://github.com/railcraft-reborn/railcraft/assets/41323182/3e6a7469-79c3-4811-8b9f-8a28551a4762)

Track layout after, version 1.0.10:
![2024-02-24_22 46 19](https://github.com/railcraft-reborn/railcraft/assets/41323182/c1e5e33b-d199-4f21-ba2f-6c0ffc92adf2)

I was able to replace the curved track after adding the switch track to get around this bug, however it appears that **this only works in a certain direction** (I need to check if it was west/east or north/south).

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.1.46

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Lay down any track in the same layout as shown in the first screenshot.
2. Add a switch track using a spike maul to connect the main line to the diverging line.

### Expected behavior

Curved track remains unchanged and connected to the switch track, just like in 1.0.2.

**Comment by Edivad99** [comment]
Try with this and tell me if the bug is still present
https://github.com/railcraft-reborn/railcraft/actions/runs/8132412102/artifacts/1293106939

**Comment by greeeen-dev** [comment]
Works properly with the patch in all four directions :+1: 
![2024-03-03_23 39 51](https://github.com/railcraft-reborn/railcraft/assets/41323182/1fd9b478-5f06-4a98-846c-be666a8156d8)
