### ISSUE TITLE
Cargo Cart

### ISSUE THREAD

**Issue by Haste29** [railcraft-reborn/railcraft#191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Hey, im not sure if it was removed or somethings glitched with crafting recipes but i cant see cargo cart in NEI or Creative Menu, it uses a similar recipe to a chest minecart but i use to love the cargo carts in 1.12.2 they were so cool>

any thoughts or anything i should know.

### Railcraft Reborn version

1.1.0

### NeoForge/Forge version

47.2.20

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

place cart and chest into crafting table (old rail craft you use to have to use a trapped chest)
makes chest minecart instead of cargo cart

### Expected behavior

i want to be able to craft a cargo cart even if it uses more resources than it use too. thanks

**Comment by Edivad99** [comment]
The cargo cart has not yet been implemented, close this issue and reopen it as a feature request
