### ISSUE TITLE
[1.20.1] Filling Immersive Engineering wooden barrel with cresorte oil causes crash

### ISSUE THREAD

**Issue by DoctorMage** [railcraft-reborn/railcraft#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Filling wooden barrel to capcity will cause crash

in regards to crash report this was originally found in a modpack causing a "Exception ticking world" 

### Railcraft Reborn version

railcraft-reborn-1.20.1-1.1.0.jar

### NeoForge/Forge version

47.2.14

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Place wooden barrel
2. get cresorte oil from railcraft
3. begin to put cresorte into barrel
4. after being filled to capcity game crashes

### Expected behavior

Begin to put cresorte oil inside barrel once filled game will not crash

### Screenshots & Video

https://gist.github.com/DoctorMage/0f496a15d507cc4b00955a2661270009

https://gist.github.com/DoctorMage/a77b907159a7100a67e9bef0345eecc0

**Comment by Edivad99** [comment]
Try with this: https://github.com/railcraft-reborn/railcraft/actions/runs/8580377290/artifacts/1390622813
