### ISSUE TITLE
thermal dynamics cables do not connect the texture to the steam boiler

### ISSUE THREAD

**Issue by imBL4CK** [railcraft-reborn/railcraft#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

the texture of the fluiducts and fluxducts does not connect to the steam boiler, but they work normally

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

47.2.19

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Place fluid/fluxducts, 2. make the stamboiler structure, 3. observe the texture that does not visually connect

### Expected behavior

I expected the texture to connect to the steam boiler

### Screenshots & Video

![2024-04-07_11 39 29](https://github.com/railcraft-reborn/railcraft/assets/160023261/8da22041-1425-4a0a-9976-b1099de30199)

**Comment by Edivad99** [comment]
If the pipe textures don't connect and the fluid still comes out, I think it's a thermal problem. Report it to them
