### ISSUE TITLE
Missing recipe for charge wire spool medium and lagrge

### ISSUE THREAD

**Issue by Chris2000SP** [railcraft-reborn/railcraft#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Playing Direwolf20 1.20 Pack and missing charge wire spool recipes.

### Railcraft Reborn version

1.0.10

### NeoForge/Forge version

47.1.84

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Open JEI to get recipe for "Medium Charge Wire Spool".
Can not craft it though.

### Expected behavior

Find "Medium Charge Wire Spool" in JEI and is able to craft.

**Comment by Edivad99** [comment]
<img width="727" alt="Screenshot 2024-04-14 alle 11 30 57" src="https://github.com/railcraft-reborn/railcraft/assets/25778604/4f6d5e7e-2ac2-4e65-85b2-4d53c3ce40af">
