### ISSUE TITLE
Regex matching in routing tables does not work

### ISSUE THREAD

**Issue by radostin04** [railcraft-reborn/railcraft#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Regex matching (with the ?= operator for Name and Dest) does not function. Even when the string should be match, a routing detector never produces an output and routing switches never switch

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

NeoForge 47.1.101

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Place a track and a routing detector next to it
2. Place a locomotive on the track and give it a ticket with a destination such as "Test"
3. Place a routing table inside the routing detector, with some regex that should match the string set in the ticket. For example, for the destination Test, `Dest?=Test`, `Dest?=Test$` and `Dest?=.*` should all match.

### Expected behavior

The routing detector should produce a redstone signal when the regex defined in the routing table matches the locomotive's ticket

### Screenshots & Video

![image](https://github.com/railcraft-reborn/railcraft/assets/19578811/7c0b2443-9a11-4e2b-9336-5449adacd257)
![image](https://github.com/railcraft-reborn/railcraft/assets/19578811/cf601b12-3995-40f6-8ff3-bbc40196b8dc)
![image](https://github.com/railcraft-reborn/railcraft/assets/19578811/12dcbdd1-0aa0-4449-888a-a0517eb82102)
![image](https://github.com/railcraft-reborn/railcraft/assets/19578811/cfe49df9-b820-4872-ac06-f1d1c7863d1b)

**Comment by Edivad99** [comment]
Try with this: https://github.com/railcraft-reborn/railcraft/actions/runs/8720670970/artifacts/1421635428

**Comment by radostin04** [comment]
Thank you, the issue is resolved in that build
