### ISSUE TITLE
Deactived the joining message

### ISSUE THREAD

**Issue by SikiciBebek** [railcraft-reborn/railcraft#203]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

![image](https://github.com/railcraft-reborn/railcraft/assets/98269183/904e5f9b-b27d-48a2-baf7-6d2d0d619156)
I would love a config where i can deactivated this message :D

**Comment by Edivad99** [comment]
There is already: https://github.com/railcraft-reborn/railcraft/blob/21fcb74b1729ff2802242ab189a39de137e489ff/src/main/java/mods/railcraft/RailcraftConfig.java#L273

**Comment by SikiciBebek** [comment]
I cant change the modpack file because of Curseforge. It would be great, if u add this in the configs.

**Comment by Edivad99** [comment]
It is in the config

**Comment by SikiciBebek** [comment]
Where ?
I cant find it in the configs oder serverconfigs?

**Comment by Edivad99** [comment]
The file's name is `railcraft-client.toml`

**Comment by SikiciBebek** [comment]
Ty :)
