### ISSUE TITLE
Steam Locomotive fluid sharing mechanics do not appear to be working

### ISSUE THREAD

**Issue by ShoobFloof22** [railcraft-reborn/railcraft#205]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the Bug

Locomotives have inventory sharing mechanics in Railcraft 1.12, and as such that means you can attach a chest full of fuel behind the locomotive for it to pull from, or a tank cart full of water for it pull from. Whenever it drops below half water, or burns one full stack of fuel from it's buffer, it will pull from the chest or tank cart behind it. In Railcraft Reborn, this only partially works. Chests work, the locomotive will pull fuel from them. I tested it by fueling an engine with sticks and having it linked to a cart behind it with more sticks in it. It pulled a stack of sticks when it had burned through one. Fluids however, do not. I was able to completely drain a locomotive of water while the tank connected behind it was still full of water. I am assuming this feature is implemented, given that there are config options to change how faster water moves from the tank to the locomotive, but it does not appear to be functional

### Railcraft Reborn version

Railcraft Reborn 1.1.1

### NeoForge/Forge version

Forge 47.2.30

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Place Steam Locomotive
2. Place Minecart with Tank behind it
3. Link the two together
4. Fuel the locomotive with burnables and water to start it, and fill the tank cart behind it with water
5. Wait for the locomotive to get below 50% (3 Buckets) of water
6. At this point, water should be pulled from the tank cart, observe that it is not doing that

### Expected behavior

Expected Behavior: Under 50% water in the Steam Locomotive's internal tank, it should pull from a Tank Cart filled with water if one is directly linked. It does not do this

**Comment by Edivad99** [comment]
Try with this: https://github.com/railcraft-reborn/railcraft/actions/runs/8959631883/artifacts/1474553707

**Comment by ShoobFloof22** [comment]
Yep, that fixed it! Thank you!
