### ISSUE TITLE
Abyssal Stairs & Slabs of any variant do not drop themselves upon being mined

### ISSUE THREAD

**Issue by SephirothWS** [railcraft-reborn/railcraft#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Abyssal Stairs & Slabs of any variant do not drop themselves upon being mined using a pickaxe.

I'm assuming Stairs and Slabs of Abyssal Stone doesn't have the correct tool flagged for mining.

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

Forge 47.2.23

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Craft Abyssal Stairs and Slab blocks.
2. Place Abyssal Stairs and Slab blocks.
3. Equip Pickaxe
4. Mine Abyssal Stairs and Slab blocks.
5. Watch as hardness of blocks cause mining to take a longer time than standard stairs and slabs.
6. Finish breaking Abyssal Stairs and Slab blocks.
7. Watch as no drops are produced.

### Expected behavior

Mining Abyssal Stairs and Slab blocks with pickaxe causes the stairs and slabs to drop themselves.

### Screenshots & Video

Compared to standard blocks, the mod Jade does NOT show a pickaxe in its tooltip when looking at these blocks.
![image](https://github.com/railcraft-reborn/railcraft/assets/9165737/12cf71f9-1cec-4540-8594-fffb377ecd4d)
![image](https://github.com/railcraft-reborn/railcraft/assets/9165737/0946d4a9-ddd2-4239-90e6-815f20562d06)

**Comment by Edivad99** [comment]
Nice catch! 🔥
Could you try with this and tell me if it is fixed
https://github.com/railcraft-reborn/railcraft/actions/runs/9006167523/artifacts/1485096113

**Comment by SephirothWS** [comment]
@Edivad99 Can confirm this snapshot has fixed the issue. Thank you.
