### ISSUE TITLE
Allow additional fuels for the fluid boiler via datapack / config

### ISSUE THREAD

**Issue by LeoBeliik** [railcraft-reborn/railcraft#209]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

As for now fluid boilers only work with creosote, would be nice to be able to add different fuels from other mods with a datapack or an option in RR's config, allowing to add fluid tag and the amount of heat they produce.

**Comment by Gunner76th** [comment]
Is there any update on this ability being added, or if it has been added, which version was this added in? Being restricted to only using creosote when some modpacks have 6+ fuels... Would really like to be able to set the firebox to be able to accept different fuels.

Hopefully this is being worked on and is scheduled to be added rather soon.

**Comment by Edivad99** [comment]
Sorry for being late.
So, this feature already exists in minecraft 1.21+, you can add custom fluid or fluid tag via datapack.
You can edit this file: `data/railcraft/data_maps/fluid/fluid_heat.json` and add for example another fluid:
```
{
  "values": {
    "#c:creosote": {
      "heat_value_per_bucket": 4800
    },
    "minecraft:lava": {
      "heat_value_per_bucket": 1000
    }
  }
}
```

**Comment by Gunner76th** [comment]
As we are on 1.20.1 this feature isn't part of railcraft.  There's an issue
ticket open on the railcraft website requesting this feature be back ported
to 1.20.1.

**Comment by Edivad99** [comment]
Unfortunately 1.20.1 does not have [Data Maps](https://docs.neoforged.net/docs/resources/server/datamaps/) and this would require too much work to implement a similar management. Work that is better focused on feature parity with 1.12 and bug fixes.
