### ISSUE TITLE
Clicked R with my inventory open, crashed to desktop w/ error code 1

### ISSUE THREAD

**Issue by shelbypup252** [railcraft-reborn/railcraft#215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Clicked R with my inventory open, crashed to desktop w/ error code 1

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

47.2.20

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Open inventory
2. Click R

### Expected behavior

Crash to desktop w/ error code 1

**Comment by Edivad99** [comment]
Are you sure this issue is related to Railcraft Reborn?
