### ISSUE TITLE
Supported Tracks - a new set of track like abandoned without *malus*

### ISSUE THREAD

**Issue by DevDyna** [railcraft-reborn/railcraft#216]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Description
A new set of tracks that can be suspended over gaps of terrain like abandoned tracks but without all other *malus* like cart derail

## Some ideas
- Track recipe could include aluminium (new ingot) only obtainable from cooking raw bauxite (new item/ore) on blast furnace
- Allow to place it based on player direction like scaffolding to make it more easier to build
- This tracks could have a more high *max rail over gap* to allow to build suspended bridges like between lakes

**Comment by Edivad99** [comment]
I think this feature would eliminate the use of the force track emitter
