### ISSUE TITLE
Rolling Machine Deleting Items

### ISSUE THREAD

**Issue by amenbr1** [railcraft-reborn/railcraft#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Rolling Machines will consume an extra set of input items when taking the output.
Taking one or more output items will only consume a single extra set of inputs.

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

47.2.14

### Minecraft version

1.20.1

### Minecraft server

No

### To Reproduce

1. Put two or more crafts worth of items in a Rolling Machine (either manual or powered).
2. Wait for a craft to complete and the next to begin.
3. Take the output item/s
4. Watch as one crafts worth of input items are deleted.

### Expected behavior

Input items should only be consumed like a furnace (when the craft is done 'cooking').
Input items should NOT also be consumed like a crafting table (when the output is taken)

**Comment by Edivad99** [comment]
@amenbr1 Sorry, could you make a video for me? I tried it and it works fine.

https://github.com/railcraft-reborn/railcraft/assets/25778604/efcc9f5e-1087-468f-a52e-de19584e5287

**Comment by amenbr1** [comment]
This only happens when manually taking the output and not when shift clicking to take the output.

**Comment by amenbr1** [comment]
This could be related to another bug I noticed. Rolling machines will stop auto crafting when there is only enough input items left for one more craft. You have to manually click the "Click to craft button" to get the rolling machine to craft the last item. They will stop crafting even if they are halfway through a craft and you remove enough input items to leave one craft worth.

**Comment by amenbr1** [comment]
https://streamable.com/e8psrt

This video shows the problem. Though this link expires in 2 days.
