### ISSUE TITLE
Point Motor Not Snapping

### ISSUE THREAD

**Issue by TheFlyingGamer** [railcraft-reborn/railcraft#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The Point Motor cannot connect to curved tracks in all orientations except when the trailing point is facing north.

Weird bug but causes issues when trying to make smooth curves

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

47.3.0

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Place the tracks ina formation where it goes in as one rail then goes out as 2 tracks next to each other at the point

### Expected behavior

The track will face in a straight direction

**Comment by TheFlyingGamer** [comment]
![2024-06-19_18 41 32](https://github.com/railcraft-reborn/railcraft/assets/139727269/a3b5bbf4-e4c8-40c1-8914-37f00f2a85c4)
![2024-06-19_18 41 54](https://github.com/railcraft-reborn/railcraft/assets/139727269/91179e97-f11a-48dd-a5c1-280d0c2d53a7)
![2024-06-19_18 40 56](https://github.com/railcraft-reborn/railcraft/assets/139727269/2add59ec-2a25-47da-9d0e-f9104469a3d6)
![2024-06-19_18 41 59_2](https://github.com/railcraft-reborn/railcraft/assets/139727269/38eff79a-4b47-4bd0-87bb-13236f2a4aae)

Screenshot evidence

**Comment by Edivad99** [comment]
@TheFlyingGamer Isn't this the same problem? https://github.com/railcraft-reborn/railcraft/issues/184

**Comment by Edivad99** [comment]
If yes, try with this: https://github.com/railcraft-reborn/railcraft/issues/184#issuecomment-1975269451
