### ISSUE TITLE
Creative High Speed Rails 

### ISSUE THREAD

**Issue by SinFlame** [railcraft-reborn/railcraft#222]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

Great mod with a great come back!

Would love to suggest adding in a Creative High Speed Rail that doesn't explode carts when doing turns or going up elevation. And it should be unbreakable and un-craftable in survival mode. 

Or please give permission for me to do an addon mod for this.

**Comment by Edivad99** [comment]
You can create an addon for this

**Comment by SinFlame** [comment]
Seems like mods.railcraft.world.level.block.track.behaivor.HighSpeedTrackUtil is final class and thats where it handles the explosions, hence I have to rewrite most of it due to that. 
My coding experience is only 1 week old and I can't do an addon for this without guidance.
