### ISSUE TITLE
Constant Wither

### ISSUE THREAD

**Issue by joshelgin11** [railcraft-reborn/railcraft#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Constant wither 2 effect wont go away and i wont take damage 

### Railcraft Reborn version

1.1.1

### NeoForge/Forge version

47.2.20

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

fought a green zombie boss and wither wont go away

### Expected behavior

Clear the wither effect

**Comment by Edivad99** [comment]
I don't think this is a Railcraft issue

**Comment by joshelgin11** [comment]
i figured it wasnt.... ive tried everthing to end myself IN GAME and i dont take damage and milk wont cure it.
