### ISSUE TITLE
Support for Expanded Storage Chest Carts

### ISSUE THREAD

**Issue by Rundas01** [railcraft-reborn/railcraft#227]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

First off, if the issue is with ES, then I'm sorry for bothering you. It would be amazing to have Railcraft Loaders/Unloaders recognize ES upgraded chest carts as a valid container to insert into/extract from.

**Comment by Edivad99** [comment]
This mod: https://www.curseforge.com/minecraft/mc-mods/expanded-storage ?

**Comment by Rundas01** [comment]
> This mod: https://www.curseforge.com/minecraft/mc-mods/expanded-storage ?

Exactly^^

**Comment by Edivad99** [comment]
I just contacted the mod developer, let's see what he/she says

**Comment by Edivad99** [comment]
It will be fixed in the next version of Expanded Storage

**Comment by Rundas01** [comment]
Thanks for all your efforts^^
