### ISSUE TITLE
(powered) rolling machine voids items if it's output becomes full

### ISSUE THREAD

**Issue by radostin04** [railcraft-reborn/railcraft#228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When crafting items in a rolling machine, regrdless of if it's powered or unpowered, the machine will continue crafting items even after the output slot fills with 64 items. Any items that don't fit into the slot are deleted.

### Railcraft Reborn version

1.1.4

### NeoForge/Forge version

NeoForge 47.1.101

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place a rolling machine, regarless of if powered or unpowered
2. Insert a recipie into it. Ensure it can craft more times than can fill into the output slot (for example, put 8 steel in each slot of the standard rail recipe)
3. Wait until the output slot fills up

### Expected behavior

Once the output slot fills up, the machine should stop crafting until there is enough space for the output

**Comment by Edivad99** [comment]
This bug fix will be released on both 1.21+ and 1.20.1
