### ISSUE TITLE
Feed station cannot accept all valid food types

### ISSUE THREAD

**Issue by radostin04** [railcraft-reborn/railcraft#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The feed station cannot accept all valid feed types. The types that are not accepted are:
 - Wheat Seeds, Beetroot Seeds, Pitcher Pod, Torchflower Seed: Chicken
 - Dandelion: Rabbit
 - Seagrass: Turtle

### Railcraft Reborn version

1.1.6

### NeoForge/Forge version

NeoForge 47.1.101

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place a feed station
2. Attempt to insert one of the abovelisted feed types

### Expected behavior

The feed station should accept all valid types of feed for all animals in the game

**Comment by Edivad99** [comment]
Waiting for https://github.com/neoforged/NeoForge/pull/1465

**Comment by Edivad99** [comment]
While waiting for neoforge I created a tag inside the mod
