### ISSUE TITLE
Feed station GUI does not display item tooltips

### ISSUE THREAD

**Issue by radostin04** [railcraft-reborn/railcraft#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The GUI of the feed station does not correctly display item tooltips. This issue does not occurr with other inventories, such as the rolling machines, steam oven, coke oven or blast furnace.

### Railcraft Reborn version

1.1.6

### NeoForge/Forge version

NeoForge 47.1.101

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place down a feed station
2. Hover over an item in your invetory

### Expected behavior

Item tooltips should display correctly, as in all other inventories.

### Screenshots & Video

![image](https://github.com/user-attachments/assets/7959c95d-17aa-4411-a865-67b198c12182)

**Comment by Edivad99** [comment]
Since 1.20.1 is only supported for critical bugs, this change will be released in a future release.
