### ISSUE TITLE
Memory Leak of Server Level

### ISSUE THREAD

**Issue by pietro-lopes** [railcraft-reborn/railcraft#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

There is a memory leak here, even with keys bein a weak reference, `ChargeNetworkImpl` *also* holds a server, so it is never released.

https://github.com/railcraft-reborn/railcraft/blob/9c22aa96af529f3d7b80f09ca898c0bcae697619/src/main/java/mods/railcraft/charge/ChargeProviderImpl.java#L14

### Railcraft Reborn version

1.2.1

### NeoForge/Forge version

21.1.21

### Minecraft version

1.21.1

### Minecraft server

No

### To Reproduce

Join game and exit to Main menu

### Expected behavior

No leak

### Screenshots & Video

![image](https://github.com/user-attachments/assets/07543f5e-3df7-4f4a-92d1-22a41d2b4902)

**Comment by Edivad99** [comment]
Hmm, I'm not an expert. What should I fix?
@Sm0keySa1m0n, can you take a look at it too?

**Comment by josephtarbit** [comment]
Yeah I can take a look.

**Comment by josephtarbit** [comment]
@Edivad99 That map can just be made into a fastutil Reference2ReferenceOpenHashMap and on level unload we need to remove the entry from the map.
