### ISSUE TITLE
Missing Item Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [railcraft-reborn/railcraft#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The following items are missing the following item tags:

Brass Plate: `c:plates`
Zinc Plate: `c:plates`
Ender Dust: `c:dusts`, `c:dusts/ender_pearl`
Saltpeper Dust: `c:dusts`
Zinc Ingot: `c:ingots`
Brass Ingot: `c:ingots`
Brass Gear: `c:gears`
Raw Zinc: `c:raw_materials`
Steel Sword: `c:tools/melee_weapon`

### Railcraft Reborn version

1.2.2

### NeoForge version

21.1.23

### Minecraft version

1.21.1

### Minecraft server

No

### To Reproduce

Check the tags they have.

### Expected behaviour

The items having the tags.

**Comment by Edivad99** [comment]
Ok, please make an exhaustive list of all missing tags with only Railcraft Reborn installed thanks.

**Comment by TheBedrockMaster** [comment]
Do any of these have the tags when only Railcraft Reborn is installed?

**Comment by Edivad99** [comment]
I'm telling you this because the tags: `plates`, `dusts/ender_pearl`, don't exist in NeoForge and so it's probably another mod that's adding them and there are likely more railcraft items to add.

**Comment by TheBedrockMaster** [comment]
I'll have a look, the `c:dusts/ender_pearl` one is so it can be compatible with the ender pearl dust from a couple of other mods that use that tag.
