### ISSUE TITLE
Track Switch Router - Switching too quickly

### ISSUE THREAD

**Issue by KillTyrant** [railcraft-reborn/railcraft#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The track switch router appears swap back to the default before the entirety of a train passes by. 

### Railcraft Reborn version

railcraft-reborn-1.20.1-1.0.10

### NeoForge/Forge version

47.1.84

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place Track switch router next to turnout track
2. Place Routing table in Track switch router
3. Appropriately denoted train passes routing switch and activates it

### Expected behavior

After doing the above steps, in my case. Only 4 of the attached 11 carts make it by before the track switch router deactivates

**Comment by Edivad99** [comment]
Sorry for being late, but i think you need to update to the latest version of Railcraft Reborn for 1.20.1 which is currently 1.1.7.
This problem is already fixed.
