### ISSUE TITLE
[1.21.1] Missing Steel Plate Tag via Json (datapack method)

### ISSUE THREAD

**Issue by StoneLegion** [railcraft-reborn/railcraft#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

I want to remove the steel plate via my custom pack, but the jar / source does not include a tag/json file for steel plate. 

![image](https://github.com/user-attachments/assets/921695ae-799d-45ae-9521-4d649ca843b5)

### Railcraft Reborn version

1.21.1-1.2.2

### NeoForge/Forge version

21.1.69

### Minecraft version

1.21.1

### Minecraft server

Yes

### To Reproduce

I created a datapack with the normal stuff and added a blank steel_plate.json file here:
modern_datapack\data\railcraft\tags\item

Sadly it did nothing and via the source/jar there is no steel_plate. Making me think the tag is created in another method via code making it not possible to remove via a datapack. 

### Expected behavior

To be able to datapack add, remove, tags. 

### Screenshots & Video

![image](https://github.com/user-attachments/assets/f061b76b-144f-4a9c-abfc-81a4a9b42220)

**Comment by Edivad99** [comment]
Look here: src/generated/resources/data/c/tags/item/plates/steel.json

**Comment by StoneLegion** [comment]
Thank you, My mistake and this worked perfectly.
