### ISSUE TITLE
All Locomotive Types have a "ghost Texture"

### ISSUE THREAD

**Issue by TheFlyingGamer** [railcraft-reborn/railcraft#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

All Locomotives are appearing, clear and without their colours I have applied. Even when attempting to add new locomotives the texture is still bugged out. Happened today and am unable to fix it.
![2024-10-22_18 35 42](https://github.com/user-attachments/assets/9d1dcabf-775f-4ae0-bd8b-2876f7a252f8)

### Railcraft Reborn version

1.1.7

### NeoForge/Forge version

47.3.7

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

Place down the Carts and are bugged like ghost texture.

### Expected behavior

The Creative and Electric Locomotives appear ghost clear and steam locomotives retain a grey blank texture seperate from the ones I have applied.

### Screenshots & Video

![2024-10-22_18 35 42](https://github.com/user-attachments/assets/ba136e8c-ad56-4181-be95-5560f6fe21bc)

**Comment by TheFlyingGamer** [comment]
Further testing shows this also affects certain carts

**Comment by Edivad99** [comment]
It's for halloween, if you don't want it you can go to the file `railcraft-client.toml` and set `ghostTrainEnabled` to false
