### ISSUE TITLE
weird behaviour when trying to rotate turnout tracks

### ISSUE THREAD

**Issue by SpottyTheTurtle** [railcraft-reborn/railcraft#26]
**Description of the Bug**

hitting a turnout track with a crowbar flips the direction it is facing rather than changing which way it bends in
**To Reproduce**

place a turnout track
try to get it to send trains left/right rather than what it was when you place it

**Expected behavior**

the track should match the behaviour of 1.12.2
**Screenshots & Video**

first screenshot is how it appears when placed, as you can see it's facing the wrong direction(the trains coming from below should be sent left not right.

in the second screenshot you can see what happens after hitting the rail with a crowbar. 
**Logs & Environment**

 - Full log: there's nothing in the log about it

 - Crash report (If available): 

**Additional context**
![2022-03-26_15 15 31](https://user-images.githubusercontent.com/69260662/160246111-566fe3c5-1e25-444d-bf07-9dda4428e872.png)
![2022-03-26_15 19 09](https://user-images.githubusercontent.com/69260662/160246113-7322896c-fd51-45f4-be4b-da0322e1147b.png)

**Comment by josephtarbit** [comment]
Fixed by 946519c
