### ISSUE TITLE
1.21.1 Can't craft crusher blocks

### ISSUE THREAD

**Issue by Roaringdrunk** [railcraft-reborn/railcraft#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

I'm having a bug in Railcraft Reborn 1.21.1: I can't make the crusher blocks for the rock crusher. Furthermore, the recipe doesn't even show up in the crafting table even though I have the resources(steel blocks, diamonds, pistons). I can give myself crusher blocks in Creative, but I can't craft them. All the other recipes seem to show up fine, although I haven't tested them since I'm stuck on the rolling machine, as I need dust to make bronze.

### Railcraft Reborn version

1.2.2

### NeoForge/Forge version

21.1.72

### Minecraft version

1.21.1

### Minecraft server

No

### To Reproduce

1. Insert steel block, 4 pistons, 4 diamonds in the crafting table
2. No crusher block crafting possible

### Expected behavior

After inserting the above mentioned items in the crafting table 4 crusher blocks should be craftable

### Screenshots & Video

![2024-11-11_14 54 46](https://github.com/user-attachments/assets/e1fc7ea0-63c2-4214-a87c-d8d7e1c49ca1)

**Comment by T1ckss** [comment]
Wrong recipe
I suggest at least installing JEI to find recipes easy.
Reason vanilla recipes are not showing is cause the default recipe thing in vanilla only shows if you discovered all the parts to make a item.

You haven't crafted a charged motor before.

For bronze you can craft bronze with 1 tin and 3 copper ingots in crafting table.

![crusher](https://github.com/user-attachments/assets/5911e762-1249-4f1d-83a0-ebb21c2858de)
