### ISSUE TITLE
JEI filters dragged into an Item Cart Detector turn fake items into real items and enable item spawning/duping

### ISSUE THREAD

**Issue by Nivid-IT** [railcraft-reborn/railcraft#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Also mentioned in: https://github.com/AllTheMods/ATM-9/issues/2130

Configuring the Item filter in the Item Cart Detector by dragging items from JEI into it, allow for a hopper (or other means of item extraction) placed underneath the Item Cart Detector to extract those items. These items aren't meant to exist however, this effectively spawns items into existence.

### Railcraft Reborn version

1.1.7

### NeoForge/Forge version

47.3.11

### Minecraft version

1.20.1

### Minecraft server

Yes

### To Reproduce

1. Place an Item Cart Detector
2. Place a Hopper underneath the Item Cart Detector
3. Set the Item Cart Detector to Filter items
4. Drag any item from JEI into an item filter slot
5. The Hopper will extract the filter as an actual item, spawning it into existence

### Expected behavior

For the Hopper not to pull out ghost items from the Item Filter which was configured using JEI

**Comment by T1ckss** [comment]
Can confirm the dupe issue exists for versions 1.2.2 and 1.2.3

**Comment by Edivad99** [comment]
I will solve for both 1.21 and 1.20
