### ISSUE TITLE
RailCraft Bug, adding modpack

### ISSUE THREAD

**Issue by HDCrazyHD** [railcraft-reborn/railcraft#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When i add in modpack, the modpack dont open
[debug-1.txt.log](https://github.com/user-attachments/files/17807733/debug-1.txt.log)

### Railcraft Reborn version

1.21.1-1-2-4

### NeoForge/Forge version

Neo Forge 21.1.80

### Minecraft version

1.21.1

### Minecraft server

Yes

### To Reproduce

Just dont open minecraft

### Expected behavior

Just dont open minecraft

**Comment by T1ckss** [comment]
Honestly looks like nothing to do with railcraft and something to do with one of the performance mods or iris that you added that is changing the rendering system.

From what I can see you are using ATM modpack and tossing mods in there... and a mod that is doing some mixins to change renderer is conflicting.
