### ISSUE TITLE
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by rsp4jack** [railcraft-reborn/railcraft#33]
**Description of the Bug**

Railcraft tried to load client-only class in server.

**To Reproduce**

1. Start a Minecraft server with Railcraft

**Expected behavior**

Start normally

**Screenshots & Video**

**Logs & Environment**
https://pastebin.com/ueSW1aEx

**Additional context**

Minecraft 1.16.5

**Comment by Edivad99** [comment]
Hi, we are currently working on Minecraft 1.19.x. 
Minecraft 1.16.5 is no longer supported and is far behind with things added/fixed
