### ISSUE TITLE
Can't open interface of Track layer/Track remover

### ISSUE THREAD

**Issue by OzzyFox** [railcraft-reborn/railcraft#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

Hello
Can't open inteface of Track layer/Track remover
1.19.2

### To Reproduce

.

### Expected behavior

.

### Screenshots & Video

![image](https://user-images.githubusercontent.com/67966949/191057662-9388c8db-909a-4025-b6e5-6a4003458e59.png)

**Comment by Edivad99** [comment]
Track Remover Cart does not have a GUI
