### ISSUE TITLE
Crushers can share walls

### ISSUE THREAD

**Issue by Thepigcat76** [railcraft-reborn/railcraft#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The Crusher can share walls with other crushers which will bug it out

breaking those bugged blocks wont even destroy the multiblock!

### To Reproduce

Issue/how to reproduce:
![2022-10-17_14 28 00](https://user-images.githubusercontent.com/93595333/196177629-7042b342-afb9-4215-b31f-9fc6100bc4dd.png)

Place the missing block

![2022-10-17_14 28 10](https://user-images.githubusercontent.com/93595333/196177695-bc7f8928-03ce-4e5f-9af6-2f1ca6cfec71.png)

### Expected behavior

I expect the multiblock to not wall share

**Comment by josephtarbit** [comment]
Fixed by d5de72a
