### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by Nomanoclass** [railcraft-reborn/railcraft#83]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe what you would like added or changed

We'd have to put the anchors back.
Or better, make the entire train to keep the chunks active without needing a special minecart.

**Comment by Edivad99** [comment]
https://discord.com/channels/225184360049934336/225184360049934336/1077630412190392441

**Comment by Nomanoclass** [comment]
Okay thanks, so if I understand correctly it should already be working.
So since it's not working, should I create a bug ticket?

**Comment by Edivad99** [comment]
It would be better. In the description explain well what you used to test
