### ISSUE TITLE
Signal reset

### ISSUE THREAD

**Issue by Nomanoclass** [railcraft-reborn/railcraft#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

The signals reset each time the world is reloaded.

### Configuration

```Markdown
- Mod version: 1.0.1
- Forge version: 47.1.1
- Minecraft version: 1.20.1
- Are you playing on a server?: no
```

### To Reproduce

1. Place Signal Receiver Box
2. Change Green To Yellow and Red
3. Save and quit to title
4. Join the last map
5. Open signal box

### Expected behavior

The Signal Receiver Box keep Yellow and Red.

### Screenshots & Video

https://github.com/railcraft-reborn/railcraft/assets/4950772/09d9c107-2a4e-44d3-9651-9ae7f35ada82

**Comment by Edivad99** [comment]
Nice catch!
