### ISSUE TITLE
Steam boiler eat resourses

### ISSUE THREAD

**Issue by OzzyFox** [railcraft-reborn/railcraft#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

It wanish coal from additional fuel slots

And it wanish water buckets too

### Configuration

```Markdown
- Mod version:railcraft-reborn-1.20.1-1.0.0
- NeoForge/Forge version:47.1.0
- Minecraft version:1.20.1
- Are you playing on a server?:no
```

### To Reproduce

1. Place solid steam fluid boiler
2. Add extra fuel to it

### Expected behavior

Check video

### Screenshots & Video

https://github.com/railcraft-reborn/railcraft/assets/67966949/4d231f30-62c7-41b6-9549-538986654c1e

**Comment by Nomanoclass** [comment]
Yes same with Steam Locomotive, fuel (uses all left cells, only if the left first cell is filled) and water bucket (dont return empty bucket).
![2023-08-19_12 38 49](https://github.com/railcraft-reborn/railcraft/assets/4950772/9415fc62-0335-45e0-b91c-1532aaef3a58)

**Comment by Edivad99** [comment]
The steam boiler bug is fixed, now I look at the locomotive
