### ISSUE TITLE
Block Signal/Receiver/Train Hold not functioning

### ISSUE THREAD

**Issue by JSDrums1** [railcraft-reborn/railcraft#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

When using the 'hold train' rail with a direct powered redstone source, i.e. a lever, it works perfectly... train is held on no power, and released when powered. However, when you add signals/receivers to the equation, the track no longer funtions properly and whether powered or not, holds the train still.

### Configuration

```Markdown
- Mod version:1.0.2
- NeoForge/Forge version: Forge 47.1.0
- Minecraft version: 1.20.1
- Are you playing on a server?: Local Test World
```

### To Reproduce

Create track with receiver under Train Holding Track
Link receiver to a signal on a seperate track
Run trains through combinations of one/both tracks
See that powered or not, the holding track still holds the train
![2023-08-21_13 28 50](https://github.com/railcraft-reborn/railcraft/assets/134440015/b3364455-e427-499a-864d-09a2d3ebf8dd)
![2023-08-21_13 28 57](https://github.com/railcraft-reborn/railcraft/assets/134440015/01ff3bc3-ed96-480c-b983-28dbf3e9f761)

### Expected behavior

When a block signal sends a 'red signal' to the holding rail, should hold the train
When it's a 'green signal' being sent, should allow the train to pass

(or visa versa)

### Screenshots & Video

![2023-08-21_13 31 37](https://github.com/railcraft-reborn/railcraft/assets/134440015/05e0ab4a-97c3-4758-860c-a34d37b620b8)
![2023-08-21_13 31 44](https://github.com/railcraft-reborn/railcraft/assets/134440015/ee76d9dc-bf08-45d6-aa4e-7df2baa4af12)

**Comment by Edivad99** [comment]
For me it works. I didn't understand what's wrong. In the receiver you can change when to emit redstone signal
![2023-08-21_17 42 04](https://github.com/railcraft-reborn/railcraft/assets/25778604/85b9df9c-9c96-4c6b-9ea3-d577b737dac3)
![2023-08-21_17 41 55](https://github.com/railcraft-reborn/railcraft/assets/25778604/307a858f-3e96-4b06-bf8f-979e61f60b7a)

**Comment by Edivad99** [comment]
Do you confirm that if the receiver is on the side, the problem doesn't exist?

**Comment by JSDrums1** [comment]
Ah. Yes that's correct, on the side it works fine.... Just when the received is beneath it doesn't work.The tutorial I watched showed it underneath, apologies.On 21 Aug 2023 16:57, Davide Albiero ***@***.***> wrote:
Do you confirm that if the receiver is on the side, the problem doesn't exist?

**Comment by Edivad99** [comment]
You were right to report this bug, it should work from below as well.

**Comment by JSDrums1** [comment]
Brilliant, thank you for letting me know that, thought I'd wasted your time at first!On 21 Aug 2023 18:54, Davide Albiero ***@***.***> wrote:
You were right to report this bug, it should work from below as well.

**Comment by Edivad99** [comment]
The problem is that the cart stalls before it enters the rail that is at the top of the receiver.
![2023-08-21_21 29 58](https://github.com/railcraft-reborn/railcraft/assets/25778604/f102bfb7-358a-4f8a-afa1-3482f63e7f13)

**Comment by JSDrums1** [comment]
I did wonder, I'm in a test world currently and noticed that the cart/loco wasn't going all the way onto the trackOn 21 Aug 2023 20:31, Davide Albiero ***@***.***> wrote:
The problem is that the cart stalls before it enters the rail that is at the top of the receiver.
