### ISSUE TITLE
quarry marker cant craft 

### ISSUE THREAD

**Issue by Tolgajk3** [railcraft-reborn/railcraft#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

no craft recip

### Configuration

```Markdown
- Mod version: quarryplus
- NeoForge/Forge version: 0.0.55
- Minecraft version: 1.20.1
- Are you playing on a server?: on my server
```

### To Reproduce

no crafting 

### Expected behavior

lapis and redstone in google craftable the marker but in game cant craft

**Comment by Edivad99** [comment]
Wrong mod
